### ISSUE TITLE
Sample without camera feed recizing

### ISSUE THREAD

**Issue by L4Hacks** [asus4/tf-lite-unity-sample#149]
**Is your feature request related to a problem? Please describe.**
After playing with all the scenes and trying to figure out how to properly scale the camera view, still cant do it properly. I found out that the TF code has a "recize" function which is cropping the camera texture in a square format.

**Describe the solution you'd like**
A simple way to use the camera image AS-IS, without cropping it.

**Comment by asus4** [comment]
The input image needs to be cropped or padded because most models (excepts Meet segmentation) accept the square size image as an input. Try to modify the following setting to `Fit` or `None` in your subclass for other resizing modes.

https://github.com/asus4/tf-lite-unity-sample/blob/26e49bf4a45a550f84f12635a97102a3e207009e/Packages/com.github.asus4.tflite.common/Runtime/BaseImagePredictor.cs#L55
