### ISSUE TITLE
ArgumentException: Object must be an array of primitives.

### ISSUE THREAD

**Issue by twister11211** [asus4/tf-lite-unity-sample#173]
hi I'm using a custom tflite model that has a input shape of [1,1] and a data type of int32
I'm trying to format a multidimensional array like this
int[][] jaggedArray = new int[1][];
        jaggedArray[0] = new int[] {43,52,55,11,60,45,46};
        var inputs0 = jaggedArray;
but when I call  interpreter.SetInputTensorData(0, inputs0);
I get the error 
ArgumentException: Object must be an array of primitives.
I don't understand what's happening as I'm using only int  is there something I'm doing wrong iv been stuck on this for a while
if any one can help it would be greatly appreciated

**Comment by asus4** [comment]
If the model input is `[1, 1]` and you are assigning an array of 7 int32, the error seems to be the expected behaviour. You should use `[1, 1]` array as input.

But I'm not sure that the model with one int32 input model is the normal model format. Did you set the input size when exporting the TFLite model?

**Comment by twister11211** [comment]
Your right I'm missing the resize_tensor_input  it was done in python with 
input_details = interpreter.get_input_details()
interpreter.resize_tensor_input(input_details[0]['index'], [1, len(input)])

is there a way to do this in C# I looked at all of the samples and couldn't find it in any of them
