### ISSUE TITLE
More info than issue.

### ISSUE THREAD

**Issue by amadlover** [asus4/tf-lite-unity-sample#22]
Hello.

Could you please tell me how did you compile the tf lite library files for the different platforms? are they available online? 

Best Regards,
Nihal Kenkre

**Comment by asus4** [comment]
@amadlover There are too few documentations to build TFLite C-APIs that you actually have to refer to the babel files in the TensorFlow repository.  I recently added a python script to build them. it might throw errors since TFLite is updated frequently, but I hope it is helpful to you.

https://github.com/asus4/tf-lite-unity-sample/blob/master/build_tflite.py
