### ISSUE TITLE
Running Android GPUDelegate in BG thread fails on API Level 31

### ISSUE THREAD

**Issue by SusheelNath** [asus4/tf-lite-unity-sample#263]
**Environment:**
 - OS/OS Version: Android API Level 31
 - Source Version: master
 - Unity Version: 2021.3.13f1

**Describe the bug**
- Current Unity version for source (master) tf-lite-unity-sample is 2020.3.36f1
- Upgrading that to **2021.3.13f1** and deploying it on Android causes the error to arise.
- TensorflowLite BlazePose **does not work anymore with Android API Level 31**.
- It works with lower Android API levels.
- On API Level 31, It works with RunBackground Off however with poorer performance.
- This is specific to Android only. It works on iOS.

**To Reproduce**
1. Clone tf-lite-unity-sample master
2. Download Unity 2021.3.13f1
3. Upgrade project and set **RunBackground On.**
4. Set API Level 31 for Android
5. Deploy .apk and test on Android mobile phone

**Expected behavior**
TensorFlowLite BlazePose should work, with RunBackground toggle on, implying smoother experience.

**Screenshots**
(https://user-images.githubusercontent.com/33517815/203538438-22984ef1-a0f9-4987-a3c2-56a8c93a9a1a.jpeg)

**Comment by asus4** [comment]
Hi @SusheelNath, could you look at #269? Changing the API level from 31 to 30 might fix this issue.

**Comment by SusheelNath** [comment]
Hi Koki,

Thank you for your response on this issue. I will try this out and keep you
posted.

Warm regards,
Susheel

**Comment by SusheelNath** [comment]
Hi Koki,

We tried with adding the lines to the AndroidManifest.xml file.
The problem still persists, RunBackgroundOn with API Level 31 - > Not working.

**Comment by SusheelNath** [comment]
Hi @karahanoguzhan  I wasn't able to unfortunately.

@asus4 Is there any other pathway that I can try out to solving this?

**Comment by asus4** [comment]
@SusheelNath  Sorry for the wait, I'll look into it when I find the time.

**Comment by asus4** [comment]
Also, I would appreciate any detailed adb log including the Android model name, version etc to determine the issue.

**Comment by asus4** [comment]
Hi @SusheelNath @karahanoguzhan, I looked into this today. 

On my Androids - tested with Google Pixel 6 and Sony Xperia XZ2, adding the `<uses-native-library>` tags in AndroidManifest.xml seems to fix the issues.

## Steps:

In Unity 2021 LTS, the legacy way of creating a file at `Plugins/Android/AndroidManifest.xml` seems outdated. Here are detailed steps to build it:

1. In the Build Settings window, enable the "Export Project" option and export an Android project instead of building an apk directly from Unity
2. Open `unityLibrary/manifests/AndroidManifest.xml` and add the following lines:
```xml
    <uses-native-library android:name="libOpenCL.so" android:required="false" />
    <uses-native-library android:name="libOpenCL-car.so" android:required="false" />
    <uses-native-library android:name="libOpenCL-pixel.so" android:required="false" />
```
![androidmanifest](https://user-images.githubusercontent.com/357497/213744371-6816e189-ac59-4db0-b9ad-8e9f61ba56f5.png)
3. Maybe you need to upgrade the Gradle version to the latest `7.2.1` as I got an error "<used-native-library> tag is unknown."
4. Remove the line 'android.enableR8' from the file `Gradle Scripts/gradle.properties`.
![android-enableR8](https://user-images.githubusercontent.com/357497/213746884-3fa6a802-6d2d-4c72-b37a-5a12e101b072.png)

Then, I succeeded in running BlazePose with the background option.

---

I suppose the reason for this error is the fallback system in the Android GpuDelegate. The default priority of the GpuDelegate is OpenCL, then fallback to OpenGLES if OpenCL is not supported on your device. And as of Android API level 31, you have to add the [uses-native-library](https://developer.android.com/guide/topics/manifest/uses-native-library-element) tag to access the OpenCL library.

Could you help us if the above steps also fix the issues on your devices? If it solves the error, we can probably make these changes automatically by implementing [IPostGenerateGradleAndroidProject](https://docs.unity3d.com/ScriptReference/Android.IPostGenerateGradleAndroidProject.html).

**Comment by SusheelNath** [comment]
Hi @asus4 @karahanoguzhan,

The above fix works. Tried it out on Samsung Galaxy S10FE & Samsung Galaxy S21.
Thank you for your efforts in this.

If you could kindly reflect this fix on your repository as well as your UPM packages? It would be a great help not only for our side but also to any other developer who comes across this issue.

Appreciate it and once again, thank you Kiki.

Warm regards,
Susheel

**Comment by SusheelNath** [comment]
Hi @asus4, I have given the performance a try with the fix. 

**Issue:** For API Level 31 and even lesser, the RunBackgroundOn performs **_worse_** than RunBackgroundOff. 
**Findings:** This is the same findings with your base repository as well. 
**Background:** Earlier in your repository (potentially before the Tensorflow package upgrades?), it used to be the other way around, where RunBackgroundOn used to perform much better than RunBackgroundOff.
Questions: 1) Is there any changes to be done to your code base for this? 
                   2) Was this intended? 
                   3) Is there any steps that can be done from our side to make the performance better? (with any, RunBackgroundOn/Off)

**Comment by asus4** [comment]
@SusheelNath  Is it only happening on Android? If so, it might be related to #243.

There are no clues right now. If we could determine from which commit this slowdown issue happens, we would have a better indication of the cause.

Anyway, can you open a new issue for the performance issue?

**Comment by SusheelNath** [comment]
@asus4 Hi Koki, I will do so. I will create a new thread to mark the performance issue.
 
I will let you close this issue yourself so that you can keep track of the fix to be implemented in your repository and the packages.

Appreciate your help on this.

**Comment by asus4** [comment]
Found more 
https://lightship.dev/docs/ardk/ardk_fundamentals/building_android.html

**Comment by asus4** [comment]
Right, would be nice if we could automate the above modification on the Android project in the [post-process build](https://docs.unity3d.com/ScriptReference/Callbacks.PostProcessBuildAttribute.html).

**Comment by asus4** [comment]
- #316

I simplified that process at the PR #316. You only need to do is adding the following tags in your custom AndroidManifest.xml 🎉 

```xml
<uses-native-library android:name="libOpenCL.so" android:required="false"/>
<uses-native-library android:name="libOpenCL-car.so" android:required="false"/>
<uses-native-library android:name="libOpenCL-pixel.so" android:required="false"/>
```
