### ISSUE TITLE
undefined symbol errors on Xcode

### ISSUE THREAD

**Issue by cancaglar** [asus4/tf-lite-unity-sample#329]
- OS/OS Version: monterey 12.6
 - Xcode version: 13.2
 - Source Version: latest
 - Unity Version: 2022.3.12
 I just download the latest version of project and just hit the iOS build and get these bunch of symbol errors. I need your help.
 
<img width="2880" alt="Ekran Resmi 2023-12-08 10 33 37" src="https://github.com/asus4/tf-lite-unity-sample/assets/59360242/381d268b-a41a-4b44-8054-4b28b3d3804e">

**Comment by asus4** [comment]
@cancaglar Thanks for reporting the issue.

To clarify the issue, could you let me know if you downloaded the repo as a zip file? If so, you need to use Git and Git-LFS to get the TensorFlow Lite libraries. Please confirm the file size at `Packages/com.github.asus4.tflite/Plugins/iOS/TensorFlowLiteC.framework`, which should be around 23MB. Otherwise, I don't have any clue for now as it is working on my end. Please paste the complete error message here to figure out the issue.

My environment:
- Xcode 15.0
- macOS Ventura 13.6.2
- Unity 2022.3.12f1

**Comment by cancaglar** [comment]
@asus4  Sorry for late reply and yes I downloaded as zip... I tried with git and now I'm can build the project. Thank you so much!
