### ISSUE TITLE
This TensorFlow Lite and the one Xamarin - identical?

### ISSUE THREAD

**Issue by tabatinga0x00** [asus4/tf-lite-unity-sample#331]
Is there any difference between this TensorFlowLite package/assembly and the one of Xamarin?

Also, can these dependencies be used in a **standard, console application** in C#? How?

```
  "dependencies": {
    // Core TensorFlow Lite libraries
    "com.github.asus4.tflite": "2.15.0",
    // Utilities for TFLite
    "com.github.asus4.tflite.common": "2.15.0",
    // Utilities for MediaPipe
    "com.github.asus4.mediapipe": "2.15.0",
    ...// other dependencies
  }
```

I haven't found any way

**Comment by asus4** [comment]
Hi @tabatinga0x00, 

I haven't tested Xamarin's version or other console apps. But I don't think these packages work outside of Unity, since the core implementation is modified for Unity. such as below:

https://github.com/asus4/tf-lite-unity-sample/blob/7eb841ea486abce4837ecee0fbc30868a1efce70/Packages/com.github.asus4.tflite/Runtime/Interpreter.cs#L241-L247

This repository has started as a fork of [TFLite's TensorFlowLitePlugin](https://github.com/tensorflow/tensorflow/tree/861d5b3a1021d3f3a77b73675c838bdaa43b0cfc/tensorflow/lite/experimental/examples/unity/TensorFlowLitePlugin). And now, various features for Unity have now been added.
