### ISSUE TITLE
Blazepose runs very slowly on mobile

### ISSUE THREAD

**Issue by cancaglar** [asus4/tf-lite-unity-sample#336]
Blazepose example runs very slowly on mobile, especially on Android and the landmarks are shaking a lot. Is there a way to reduce this? I want to make it smoother.

**Comment by asus4** [comment]
Hi, @cancaglar. Implementation in the Blazepose pre/post-process is a bit different from the original MediaPipe's, and models still need to be updated. I want to update them when I have some time. Also, PR is welcome 👍 

In terms of performance, can you check it with the original MediaPipe? It might be slow even with the original implementation in some low-end Android since the Boty tracking is a heavy process.
