### ISSUE TITLE
Determining Face Rotation In FaceMesh Sample

### ISSUE THREAD

**Issue by cancaglar** [asus4/tf-lite-unity-sample#364]
Hello, I am trying to determine if a face is looking at the screen in the FaceMesh example. To do this, I need the rotation of the face. I have tried a bit but couldn't manage it. I looked into how it's done with MediaPipe in Python, but couldn't find much useful information. Can you help me with this?

**Comment by stephahn** [comment]
Hello
if it is still an issue, I succeed to have rotation around the 3 axes using the Kabsch algorithm with data input being the predicted landmarks, and the canonical face model. That output are the yaw,  pitch and roll (I added the scale also in the resolution). 

Otherwise, mediapipe has in his solution a transformation matrice as output that should contains the rotations. 

For speed purpose I recommend to code it in C++ with Eigen library.
