### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by Roberto7766** [asus4/tf-lite-unity-sample#77]
**Environment**
 - OS/OS Version: Andoroid 9
 - Unity Version: Unity 2019.4.12.f1

**Describe the bug**
All the samples runs well on the PC (using PC webcam) but when I build and run for Android only a white rectangle appears and nothing happens. The only sample I was able to run succesfully on Android is TestWebCamRotation.
I tried different combination of Vulkan and OpenGLES3 with no success. Any hint?

**Note**
You did a really good job. Keep going!

**Comment by FrankSpalteholz** [comment]
Hi Roberto, i was facing similar issues on iOS with my iPad. In my case it had to do with the orientation (landscape, portrait etc). So most camera-sensors in smart-phones and tablets are rotated by 90 degrees and although Unity is able to compensate for that the inputTexture (WebCamTexture) is not taking account for that. In my case i had to flip the xAxes of the keypoints (1f-keypoint) and also flip uv's and normals of the face-mesh, but this only works on landscape-mode. You could also rotate your rendercam and mirror the canvas. In the end i was using OpenCV to adjust the textures how needed because it was the cleanest solution for my purposes. Hope this helps.

**Comment by asus4** [comment]
Thanks for sharing it @FrankSpalteholz 

@Roberto7766 Do you get any errors on logcat?

**Comment by Roberto7766** [comment]
Thanks @FrankSpalteholz and @asus4.
Using logcat I found out that the issue is with the neural network. If I comment the NN part the camera works well.
Here the logcat result:

2020-10-30 08:09:02.815 20668-20687/? E/Unity: DllNotFoundException: libtensorflowlite_c
        at (wrapper managed-to-native) TensorFlowLite.InterpreterOptions.TfLiteInterpreterOptionsCreate()
      at TensorFlowLite.InterpreterOptions..ctor () [0x00006] in <9d167a8ec82e4b91b0e30378348ced48>:0 
      at TensorFlowLite.BaseImagePredictor`1[T]..ctor (System.String modelPath, System.Boolean useGPU) [0x00006] in <f0bdf3e3c065439c8b47889776cb0c01>:0 
      at TensorFlowLite.SSD..ctor (System.String modelPath) [0x00035] in <f0bdf3e3c065439c8b47889776cb0c01>:0 
      at SsdSample.Start () [0x00011] in <f0bdf3e3c065439c8b47889776cb0c01>:0   

  (Filename: <f0bdf3e3c065439c8b47889776cb0c01> Line: 0)
2020-10-30 08:09:07.986 20668-20687/? E/Unity: NullReferenceException: Object reference not set to an instance of an object
      at SsdSample.Update () [0x00000] in <f0bdf3e3c065439c8b47889776cb0c01>:0

**Comment by asus4** [comment]
It seems like failing to load the TensorFlow Lite library. Please make sure that your CPU isn't 32bit. But I've confirmed some cases that 64bit Android fails as well.

**Comment by Roberto7766** [comment]
It is 64bit. What can be done to move forward? Thks.

**Comment by asus4** [comment]
The only thing I could see from the logcat is that the library is failing to load. We need to investigate the cause of the problem.

**Comment by kaiquesacchi** [comment]
I've cloned the repo and got it to work on Android, Windows and Linux. I've even added my own Image Classification model, created a new scene, loaded it and got it to work as well.

When I tried creating a new Unity project and then adding the package (using the Package Manager and selecting the package file given in the Packages folder of your repo), I only got it to work with Windows and Linux. For some reason, when using it on Android, it breaks after trying to create instances of InterpreterOptions and Interpreter.

Are you aware of any additional steps that should be performed in order to add the package to a new project?

**Comment by ganaware** [comment]
I have had a similer problem. 
The cause of the problem is that Mono is the default scripting backend for a new unity project for Android.
Unfortunately, Mono can run only for the ARMv7 architecture.

So my solution is that:
1. Project Settings > Player > Android > Other Settings > Configuration
   - Select IL2CPP for Scripting Backend
   - Uncheck ARMv7 and check ARM64 for Target Architectures
2. Or, build my own TFLite library for ARMv7
   - libnnapi_delegate.so, libtensorflowlite_c.so, libtensorflowlite_gpu_delegate.so
   - They worked fine for me.

**Comment by kaiquesacchi** [comment]
Yesterday we found out about this config and solved the problem in that exact way (the first option you suggested)!
Anyway, thank you so much for taking your time to help us. Your solution works. :) @ganaware 

> I have had a similer problem.
> The cause of the problem is that Mono is the default scripting backend for a new unity project for Android.
> Unfortunately, Mono can run only for the ARMv7 architecture.
> 
> So my solution is that:
> 
> 1. Project Settings > Player > Android > Other Settings > Configuration
>    
>    * Select IL2CPP for Scripting Backend
>    * Uncheck ARMv7 and check ARM64 for Target Architectures
> 2. Or, build my own TFLite library for ARMv7
>    
>    * libnnapi_delegate.so, libtensorflowlite_c.so, libtensorflowlite_gpu_delegate.so
>    * They worked fine for me.
